name: iitt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  camera: ^0.11.0
  

  
  choice: ^2.3.2
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  
  http: ^1.1.0
  image_picker: ^1.1.2
  
  intl: ^0.18.1
  
  location: ^5.0.3
  
  permission_handler: ^11.3.1
  razorpay_flutter: ^1.3.6 
  rename: ^3.0.2
  shared_preferences: ^2.2.2
  skeletonizer: ^1.3.0
 

flutter_native_splash:
  image: assets/icons/iittnif.png
  color: "#ffffff"
  android: true

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    
    - family: man-r
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        
  assets:
   - assets/icons/
   - assets/images/
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpeg"
  remove_alpha_ios: true

