name: iitt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_bottom_bar: ^1.2.4
  camera: ^0.11.0
  

  
  chips_choice: ^3.0.1
  choice: ^2.3.2
  custom_refresh_indicator: ^3.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  
  flutter_sliding_box: ^1.1.5
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  
  google_maps_flutter: ^2.7.0
  google_sign_in: ^6.2.1
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  
  intl: ^0.18.1
  
  location: ^5.0.3
  
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.3.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
 

flutter_native_splash:
  image: assets/icons/logo2.png
  color: "#ffffff"
  android: true

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    
    - family: man-r
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

    - family: man-b
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        
  assets:
   - assets/icons/
   - assets/images/
   - assets/gifs/
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo2.png"
  remove_alpha_ios: true

